'use strict';

const ALBUM = {
  BASE_PATH: 'v1/albums',
  ENRICHMENTS: {
    TEXT: 'text',
    LOCATION: 'location',
    MAP: 'map',
  },
  POSITION_TYPE: {
    POSITION_TYPE_UNSPECIFIED: 'POSITION_TYPE_UNSPECIFIED',
    FIRST_IN_ALBUM: 'FIRST_IN_ALBUM',
    LAST_IN_ALBUM: 'LAST_IN_ALBUM',
    AFTER_MEDIA_ITEM: 'AFTER_MEDIA_ITEM',
    AFTER_ENRICHMENT_ITEM: 'AFTER_ENRICHMENT_ITEM',
  },
};

module.exports = ALBUM;
