'use strict';

const MEDIA_ITEMS = {
  BASE_PATH: 'v1/mediaItems',
  VIDEO_PROCESSING_STATUS: {
    UNSPECIFIED: 'UNSPECIFIED',
    PROCESSING: 'PROCESSING',
    READY: 'READY',
    FAILED: 'FAILED',
  },
  CONTENT_CATEGORY: {
    NONE: 'NONE',
    LANDSCAPES: 'LANDSCAPES',
    RECEIPTS: 'RECEIPTS',
    CITYSCAPES: 'CITYSCAPES',
    LANDMARKS: 'LANDMARKS',
    SELFIES: 'SELFIES',
    PEOPLE: 'PEOPLE',
    PETS: 'PETS',
    WEDDINGS: 'WEDDINGS',
    BIRTHDAYS: 'BIRTHDAYS',
    DOCUMENTS: 'DOCUMENTS',
    TRAVEL: 'TRAVEL',
    ANIMALS: 'ANIMALS',
    FOOD: 'FOOD',
    SPORT: 'SPORT',
    NIGHT: 'NIGHT',
    PERFORMANCES: 'PERFORMANCES',
    WHITEBOARDS: 'WHITEBOARDS',
    SCREENSHOTS: 'SCREENSHOTS',
    UTILITY: 'UTILITY',
  },
  MEDIA_TYPE: {
    ALL_MEDIA: 'ALL_MEDIA',
    PHOTO: 'PHOTO',
    VIDEO: 'VIDEO',
  },
};

module.exports = MEDIA_ITEMS;
